import Header from "./components/Layouts/Header";
import Footer from "./components/Layouts/Footer";
import { Montserrat, Inter, Playfair_Display, JetBrains_Mono} from "next/font/google";
import { CrowdFundingProvider } from "../../Context/crowdfunding";

import "./globals.css";

const heading = Montserrat({
  variable: "--next-font-heading", 
  subsets: ["latin"],
});

const sans = Inter({
  variable: "--next-font-sans",
  subsets: ["latin"],
});

const serif = Playfair_Display({
  variable: "--next-font-serif",
  subsets: ["latin"],
  display: "swap",
});

const mono = JetBrains_Mono({
  variable: "--next-font-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "FundChain Crowdfunding Dapp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${sans.variable} ${heading.variable} ${serif.variable} ${mono.variable} antialiased bg-background font-font-heading text-foreground min-h-screen`}
      >
        <CrowdFundingProvider>
          <Header/>
          {children}
          <Footer/>
        </CrowdFundingProvider>
      </body>
    </html>
  );
}
